use telic::arena::{CommandTree, GameAgent, PlayerIndex};
use telic::planning::belief::{BeliefBuilder, BeliefSet};
use telic::planning::action::ActionBuilder;
use telic::planning::goal::GoalBuilder;
use telic::planning::planner::GoapPlanner;
use telic::planning::utility::{
    UtilityAction, ResponseCurve, ScoringMode, Greedy, AssignmentStrategy, ActionSource,
};

use crate::game::types::*;
use crate::game::state::SimpleWarsView;

/// Hybrid agent — demonstrates GOAP + HTN + Utility working together.
///
/// Each layer handles a different timescale:
///
/// **GOAP (strategic):** Backward-chains from goals to determine what to
/// build. "I need to capture cities → need infantry → need to build infantry."
/// Drives build order decisions.
///
/// **HTN (operational):** Decomposes the current strategic step into concrete
/// operations. "Expand" → find nearest uncaptured city → siege(city).
/// "Siege" → if defenders present: [clear defenders, capture], else: [capture].
///
/// **Utility (tactical):** Assigns individual units to the decomposed tasks
/// using coordinated scoring via the `Greedy` assignment strategy.
///
/// Integration flow each turn:
/// 1. Update beliefs from current view
/// 2. GOAP evaluates goals → picks strategic plan
/// 3. Current plan step → HTN decomposes into unit-level tasks
/// 4. Utility scores unit-task pairs → Greedy with coordination
/// 5. Execute best command
#[derive(Debug)]
pub struct HybridAgent {
    name: String,
    player: PlayerIndex,
    actions_this_turn: u32,
    explored: Vec<Vec<bool>>,
    map_rows: u8,
    map_cols: u8,
    last_known_enemies: Vec<(Pos, u32)>,
    /// Current GOAP plan step (what strategic action we're pursuing)
    current_strategy: StrategicAction,
    /// Tracks how long we've been on the same strategy
    strategy_turns: u32,
}

/// GOAP-level strategic actions (what to pursue)
#[derive(Debug, Clone, PartialEq)]
enum StrategicAction {
    /// Build infantry for capturing
    BuildCapturers,
    /// Build combat units for fighting
    BuildArmy,
    /// Expand — capture neutral cities
    Expand,
    /// Attack — engage the enemy
    Attack,
    /// Defend HQ
    Defend,
    /// Assault enemy HQ for the win
    AssaultHQ,
}

/// Strategic weight modifiers — GOAP sets the emphasis, not the constraint.
#[derive(Debug, Clone, Copy)]
struct StrategyWeights {
    capture: f64,
    attack: f64,
    defend: f64,
    advance: f64,
}

/// Operational task for a single unit (from smart objects + memory + agent)
#[derive(Debug, Clone)]
struct OpTask {
    kind: TaskKind, // from game types
    target: Pos,
    value: f64,
    /// Whether this task was generated by HTN decomposition
    from_htn: bool,
}

/// Scoring context for utility layer
struct ScoringCtx {
    unit_type: UnitType,
    unit_pos: Pos,
    task_target: Pos,
    task_value: f64,
    task_kind_idx: usize,
    hq_threat: f64,
    our_strength: f64,
    strength_advantage: f64,
    economy: f64,
    our_hq: Pos,
    near_hq: bool,
}

impl HybridAgent {
    pub fn new(name: impl Into<String>, _seed: u64) -> Self {
        Self {
            name: name.into(),
            player: 0,
            actions_this_turn: 0,
            explored: Vec::new(),
            map_rows: 0,
            map_cols: 0,
            last_known_enemies: Vec::new(),
            current_strategy: StrategicAction::BuildCapturers,
            strategy_turns: 0,
        }
    }

    // =========================================================================
    // Layer 1: GOAP — strategic planning via BeliefSet + GoapPlanner
    // =========================================================================

    /// Build beliefs from the current view, evaluate via the framework's
    /// BeliefSet<SimpleWarsView>.
    fn evaluate_strategy(&mut self, view: &SimpleWarsView) -> StrategicAction {
        // Build beliefs — each queries &view immutably
        let mut beliefs = BeliefSet::<SimpleWarsView>::new();
        let player = self.player;

        beliefs.add(BeliefBuilder::new("has_gold_for_infantry")
            .condition(move |v: &SimpleWarsView| v.our_gold >= 1000)
            .build());

        beliefs.add(BeliefBuilder::new("has_gold_for_tank")
            .condition(move |v: &SimpleWarsView| v.our_gold >= 3000)
            .build());

        beliefs.add(BeliefBuilder::new("has_capturers")
            .condition(move |v: &SimpleWarsView| {
                v.our_units.iter().filter(|u| u.unit_type.can_capture()).count() >= 2
            }).build());

        beliefs.add(BeliefBuilder::new("has_combat_force")
            .condition(move |v: &SimpleWarsView| {
                let strength: f64 = v.our_units.iter()
                    .map(|u| u.unit_type.attack_power() as f64 * (u.hp as f64 / 10.0))
                    .sum();
                strength >= 15.0
            }).build());

        beliefs.add(BeliefBuilder::new("has_economic_advantage")
            .condition(move |v: &SimpleWarsView| {
                let our_cities = v.buildings.iter()
                    .filter(|b| b.owner == Some(player)).count();
                our_cities >= 4
            }).build());

        beliefs.add(BeliefBuilder::new("hq_threatened")
            .condition(move |v: &SimpleWarsView| {
                let threat: f64 = v.visible_enemy_units.iter()
                    .map(|e| {
                        let dist = e.pos.manhattan_distance(v.our_hq).max(1) as f64;
                        e.unit_type.attack_power() as f64 / dist
                    }).sum();
                threat > 3.0
            }).build());

        beliefs.add(BeliefBuilder::new("hq_safe")
            .condition(move |v: &SimpleWarsView| {
                let threat: f64 = v.visible_enemy_units.iter()
                    .map(|e| {
                        let dist = e.pos.manhattan_distance(v.our_hq).max(1) as f64;
                        e.unit_type.attack_power() as f64 / dist
                    }).sum();
                threat <= 3.0
            }).build());

        beliefs.add(BeliefBuilder::new("enemy_hq_captured")
            .condition(|_: &SimpleWarsView| false) // terminal goal
            .build());

        beliefs.add(BeliefBuilder::new("enemy_weakened")
            .condition(move |v: &SimpleWarsView| {
                let enemy_str: f64 = v.visible_enemy_units.iter()
                    .map(|u| u.unit_type.attack_power() as f64 * (u.hp as f64 / 10.0))
                    .sum();
                enemy_str < 10.0 || v.visible_enemy_units.is_empty()
            }).build());

        // GOAP actions — what strategic steps can we take?
        let actions = vec![
            ActionBuilder::new("build_capturers")
                .cost(1.0)
                .precondition("has_gold_for_infantry")
                .effect("has_capturers")
                .strategy(NoOpStrategy)
                .build(),
            ActionBuilder::new("build_army")
                .cost(2.0)
                .precondition("has_gold_for_tank")
                .effect("has_combat_force")
                .strategy(NoOpStrategy)
                .build(),
            ActionBuilder::new("expand")
                .cost(1.0)
                .precondition("has_capturers")
                .effect("has_economic_advantage")
                .strategy(NoOpStrategy)
                .build(),
            ActionBuilder::new("attack_enemy")
                .cost(2.0)
                .precondition("has_combat_force")
                .effect("enemy_weakened")
                .strategy(NoOpStrategy)
                .build(),
            ActionBuilder::new("defend_hq")
                .cost(1.0)
                .effect("hq_safe")
                .strategy(NoOpStrategy)
                .build(),
            ActionBuilder::new("assault_hq")
                .cost(3.0)
                .precondition("has_combat_force")
                .precondition("has_economic_advantage")
                .effect("enemy_hq_captured")
                .strategy(NoOpStrategy)
                .build(),
        ];

        // Goals — prioritized
        let goals = vec![
            GoalBuilder::new("defend")
                .priority(4) // highest when threatened
                .desired_effect("hq_safe")
                .build(),
            GoalBuilder::new("win")
                .priority(3)
                .desired_effect("enemy_hq_captured")
                .build(),
            GoalBuilder::new("grow_economy")
                .priority(2)
                .desired_effect("has_economic_advantage")
                .build(),
            GoalBuilder::new("build_force")
                .priority(1)
                .desired_effect("has_combat_force")
                .build(),
        ];

        // Run the GOAP planner — backward-chains from highest-priority unsatisfied goal
        let last = match &self.current_strategy {
            StrategicAction::BuildCapturers => Some("build_force"),
            StrategicAction::BuildArmy => Some("build_force"),
            StrategicAction::Expand => Some("grow_economy"),
            StrategicAction::Attack => Some("win"),
            StrategicAction::Defend => Some("defend"),
            StrategicAction::AssaultHQ => Some("win"),
        };

        if let Some(plan) = GoapPlanner::plan(&beliefs, view, &actions, &goals, last) {
            // Take the FIRST action in the plan — that's what we should do NOW
            match plan.actions.first().map(|s| s.as_str()) {
                Some("build_capturers") => StrategicAction::BuildCapturers,
                Some("build_army") => StrategicAction::BuildArmy,
                Some("expand") => StrategicAction::Expand,
                Some("attack_enemy") => StrategicAction::Attack,
                Some("defend_hq") => StrategicAction::Defend,
                Some("assault_hq") => StrategicAction::AssaultHQ,
                _ => StrategicAction::Expand, // fallback
            }
        } else {
            // No plan found — default to expansion
            StrategicAction::Expand
        }
    }

    // =========================================================================
    // Layer 2: HTN — generate ALL tasks, apply strategic weight modifiers
    // =========================================================================

    /// Strategic weight modifiers — GOAP priority tilts scores, doesn't gate them.
    /// All task types are always available. The strategy determines emphasis.
    fn strategy_weights(&self, strategy: &StrategicAction) -> StrategyWeights {
        match strategy {
            StrategicAction::BuildCapturers => StrategyWeights {
                capture: 1.2, attack: 0.8, defend: 1.0, advance: 0.7,
            },
            StrategicAction::BuildArmy => StrategyWeights {
                capture: 1.0, attack: 0.9, defend: 1.0, advance: 0.8,
            },
            StrategicAction::Expand => StrategyWeights {
                capture: 1.5, attack: 0.8, defend: 0.9, advance: 0.7,
            },
            StrategicAction::Attack => StrategyWeights {
                capture: 0.7, attack: 1.5, defend: 0.9, advance: 1.2,
            },
            StrategicAction::Defend => StrategyWeights {
                capture: 0.5, attack: 1.2, defend: 2.0, advance: 0.3,
            },
            StrategicAction::AssaultHQ => StrategyWeights {
                capture: 1.3, attack: 1.3, defend: 0.5, advance: 1.5,
            },
        }
    }

    /// Generate ALL tasks from smart objects + memory + agent-generated.
    /// Every task type is always present — GOAP weights tilt, not gate.
    fn generate_all_tasks(&self, view: &SimpleWarsView) -> Vec<OpTask> {
        let mut tasks = Vec::new();
        let weights = self.strategy_weights(&self.current_strategy);

        // Smart objects: buildings advertise capture tasks
        for building in &view.buildings {
            for offered in building.available_actions(view) {
                let weight = match offered.kind {
                    TaskKind::Capture => weights.capture,
                    TaskKind::Attack => weights.attack,
                    TaskKind::Defend => weights.defend,
                    TaskKind::Advance => weights.advance,
                };
                tasks.push(OpTask {
                    kind: offered.kind, target: offered.target,
                    value: offered.value * weight, from_htn: false,
                });
            }
        }

        // Smart objects: enemies advertise attack tasks
        for enemy in &view.visible_enemy_units {
            for offered in enemy.available_actions(view) {
                // HTN enrichment: enemies near capture targets get a bonus
                // (clear defenders to enable capture — operational awareness)
                let near_capturable = view.buildings.iter()
                    .any(|b| b.owner != Some(self.player)
                        && offered.target.manhattan_distance(b.pos) <= 3);
                let htn_boost = if near_capturable { 1.3 } else { 1.0 };

                // Enemies near our HQ get defend-priority boost
                let near_our_hq = offered.target.manhattan_distance(view.our_hq) <= 5;
                let defend_boost = if near_our_hq { weights.defend * 0.5 } else { 0.0 };

                tasks.push(OpTask {
                    kind: offered.kind, target: offered.target,
                    value: offered.value * weights.attack * htn_boost + defend_boost,
                    from_htn: near_capturable,
                });
            }
        }

        // Memory: last-known enemy positions
        if view.visible_enemy_units.is_empty() {
            for (pos, _) in &self.last_known_enemies {
                tasks.push(OpTask {
                    kind: TaskKind::Attack, target: *pos,
                    value: 1.0 * weights.attack, from_htn: false,
                });
            }
        }

        // Defend HQ (always available, weighted by strategy)
        let hq_threat: f64 = view.visible_enemy_units.iter()
            .map(|e| {
                let dist = e.pos.manhattan_distance(view.our_hq).max(1) as f64;
                e.unit_type.attack_power() as f64 / dist
            }).sum();
        if hq_threat > 0.5 {
            tasks.push(OpTask {
                kind: TaskKind::Defend, target: view.our_hq,
                value: hq_threat * weights.defend, from_htn: false,
            });
        }

        // Advance toward enemy HQ (always available)
        tasks.push(OpTask {
            kind: TaskKind::Advance, target: view.enemy_hq,
            value: 1.0 * weights.advance, from_htn: false,
        });

        tasks
    }

    // =========================================================================
    // Layer 3: Utility — score unit-task pairs and assign with coordination
    // =========================================================================

    fn build_utility_actions() -> Vec<UtilityAction<ScoringCtx>> {
        let capture = UtilityAction::new("capture")
            .with_base(1.0).with_mode(ScoringMode::Multiplicative)
            .consider("can_capture",
                |ctx: &ScoringCtx| if ctx.unit_type.can_capture() { 1.0 } else { 0.0 },
                ResponseCurve::Identity, 1.0)
            .consider("value",
                |ctx: &ScoringCtx| ctx.task_value,
                ResponseCurve::Identity, 1.0)
            .consider("economy_need",
                |ctx: &ScoringCtx| if ctx.economy < 3.0 { 1.5 } else { 1.0 },
                ResponseCurve::Identity, 1.0)
            .consider("hq_safety",
                |ctx: &ScoringCtx| {
                    if ctx.hq_threat > 3.0 && ctx.near_hq { 0.3 } else { 1.0 }
                }, ResponseCurve::Identity, 1.0)
            .consider("inv_dist",
                |ctx: &ScoringCtx| 1.0 / ctx.unit_pos.manhattan_distance(ctx.task_target).max(1) as f64,
                ResponseCurve::Identity, 1.0);

        let attack = UtilityAction::new("attack")
            .with_base(4.0).with_mode(ScoringMode::Multiplicative)
            .consider("odds",
                |ctx: &ScoringCtx| {
                    if ctx.task_value > 1.2 { ctx.task_value } else { ctx.task_value * 0.5 }
                }, ResponseCurve::Identity, 1.0)
            .consider("strength_mod",
                |ctx: &ScoringCtx| if ctx.strength_advantage > 1.3 { 1.5 } else { 1.0 },
                ResponseCurve::Identity, 1.0)
            .consider("unit_fit",
                |ctx: &ScoringCtx| match ctx.unit_type {
                    UnitType::Tank => 1.3, UnitType::Infantry => 0.8,
                    UnitType::Artillery => 1.5, UnitType::Recon => 0.5,
                }, ResponseCurve::Identity, 1.0)
            .consider("inv_dist",
                |ctx: &ScoringCtx| 1.0 / ctx.unit_pos.manhattan_distance(ctx.task_target).max(1) as f64,
                ResponseCurve::Identity, 1.0);

        let advance = UtilityAction::new("advance")
            .with_base(1.5).with_mode(ScoringMode::Multiplicative)
            .consider("strength_mod",
                |ctx: &ScoringCtx| if ctx.our_strength > 20.0 { 2.0 } else { 1.0 },
                ResponseCurve::Identity, 1.0)
            .consider("inv_dist",
                |ctx: &ScoringCtx| 1.0 / ctx.unit_pos.manhattan_distance(ctx.task_target).max(1) as f64,
                ResponseCurve::Identity, 1.0);

        let defend = UtilityAction::new("defend")
            .with_base(1.0).with_mode(ScoringMode::Multiplicative)
            .consider("urgency",
                |ctx: &ScoringCtx| (ctx.hq_threat * 2.0).max(1.0),
                ResponseCurve::Identity, 1.0)
            .consider("unit_combat",
                |ctx: &ScoringCtx| ctx.unit_type.attack_power() as f64 / 5.0,
                ResponseCurve::Identity, 1.0)
            .consider("inv_dist",
                |ctx: &ScoringCtx| 1.0 / ctx.unit_pos.manhattan_distance(ctx.task_target).max(1) as f64,
                ResponseCurve::Identity, 1.0);

        vec![capture, attack, advance, defend]
    }

    fn build_scoring_ctx(unit: &Unit, task: &OpTask, view: &SimpleWarsView, player: PlayerIndex) -> ScoringCtx {
        let hq_threat: f64 = view.visible_enemy_units.iter()
            .map(|e| {
                let dist = e.pos.manhattan_distance(view.our_hq).max(1) as f64;
                e.unit_type.attack_power() as f64 / dist
            }).sum();
        let our_strength: f64 = view.our_units.iter()
            .map(|u| u.unit_type.attack_power() as f64 * (u.hp as f64 / 10.0)).sum();
        let enemy_strength: f64 = view.visible_enemy_units.iter()
            .map(|u| u.unit_type.attack_power() as f64 * (u.hp as f64 / 10.0)).sum();

        ScoringCtx {
            unit_type: unit.unit_type,
            unit_pos: unit.pos,
            task_target: task.target,
            task_value: task.value,
            task_kind_idx: match task.kind {
                TaskKind::Capture => 0, TaskKind::Attack => 1,
                TaskKind::Advance => 2, TaskKind::Defend => 3,
            },
            hq_threat,
            our_strength,
            strength_advantage: if enemy_strength > 0.0 { our_strength / enemy_strength } else { 2.0 },
            economy: view.buildings.iter().filter(|b| b.owner == Some(player)).count() as f64,
            our_hq: view.our_hq,
            near_hq: unit.pos.manhattan_distance(view.our_hq) < 4,
        }
    }

    fn assign_units(&self, tasks: &[OpTask], view: &SimpleWarsView) -> Vec<(u16, OpTask)> {
        let actionable: Vec<&Unit> = view.our_units.iter()
            .filter(|u| !(u.moved && u.attacked)).collect();
        if actionable.is_empty() || tasks.is_empty() { return Vec::new(); }

        let utility_actions = Self::build_utility_actions();
        let player = self.player;

        let mut scores: Vec<Vec<f64>> = actionable.iter().map(|unit| {
            tasks.iter().map(|task| {
                let ctx = Self::build_scoring_ctx(unit, task, view, player);
                utility_actions[ctx.task_kind_idx].score(&ctx)
            }).collect()
        }).collect();

        // Coordination via Greedy strategy
        let assignments = Greedy::with_coordination(|_ei, ti, scores: &mut Vec<Vec<f64>>| {
            let task = &tasks[ti];
            if task.kind == TaskKind::Capture {
                // Diminish same-target captures
                for row in scores.iter_mut() {
                    for (tj, t) in tasks.iter().enumerate() {
                        if t.kind == TaskKind::Capture && t.target == task.target {
                            row[tj] *= 0.5;
                        }
                    }
                }
            }
            if task.kind == TaskKind::Attack {
                // Focus fire on tough targets
                let is_tough = view.visible_enemy_units.iter()
                    .find(|e| e.pos == task.target)
                    .map(|e| e.hp >= 7 || e.unit_type.attack_power() >= 6)
                    .unwrap_or(false);
                if is_tough {
                    for (ui, row) in scores.iter_mut().enumerate() {
                        if actionable[ui].pos.manhattan_distance(task.target) <= 5 {
                            for (tj, t) in tasks.iter().enumerate() {
                                if t.kind == TaskKind::Attack && t.target == task.target {
                                    row[tj] *= 1.5;
                                }
                            }
                        }
                    }
                }
            }
        }).assign(&mut scores);

        assignments.iter()
            .map(|&(ei, ti, _)| (actionable[ei].id, tasks[ti].clone()))
            .collect()
    }

    // =========================================================================
    // Tactical execution (same as coordinated agent)
    // =========================================================================

    fn execute_unit(&self, unit: &Unit, task: &OpTask, view: &SimpleWarsView) -> Option<Command> {
        let uid = unit.id;

        if unit.unit_type.can_capture() && !unit.attacked {
            if view.buildings.iter().any(|b| b.pos == unit.pos && b.owner != Some(self.player)) {
                return Some(Command::Capture { unit_id: uid });
            }
        }

        if !unit.attacked && !unit.unit_type.is_ranged() {
            for enemy in &view.visible_enemy_units {
                if unit.pos.manhattan_distance(enemy.pos) == 1 {
                    return Some(Command::Attack { unit_id: uid, target_pos: enemy.pos });
                }
            }
        }

        if unit.unit_type.is_ranged() && !unit.attacked && !unit.moved {
            for enemy in &view.visible_enemy_units {
                let dist = unit.pos.manhattan_distance(enemy.pos);
                if dist >= unit.unit_type.attack_min_range()
                    && dist <= unit.unit_type.attack_max_range()
                {
                    return Some(Command::Attack { unit_id: uid, target_pos: enemy.pos });
                }
            }
        }

        if !unit.moved {
            let target = task.target;
            let mut candidates: Vec<(u8, Pos)> = Vec::new();
            for (dr, dc) in [(-1i8, 0), (1, 0), (0, -1), (0, 1)] {
                let nr = unit.pos.row as i8 + dr;
                let nc = unit.pos.col as i8 + dc;
                if nr < 0 || nr >= view.rows as i8 || nc < 0 || nc >= view.cols as i8 { continue; }
                let npos = Pos::new(nr as u8, nc as u8);
                if !unit.unit_type.can_enter(view.grid[npos.row as usize][npos.col as usize]) { continue; }
                if view.our_units.iter().any(|u| u.id != uid && u.pos == npos) { continue; }
                candidates.push((npos.manhattan_distance(target), npos));
            }
            candidates.sort_by_key(|(d, _)| *d);

            if let Some((best_dist, best_pos)) = candidates.first() {
                let current_dist = unit.pos.manhattan_distance(target);
                if *best_dist < current_dist {
                    return Some(Command::Move { unit_id: uid, to: *best_pos });
                }
                if let Some((_, pos)) = candidates.iter().find(|(d, _)| *d <= current_dist) {
                    return Some(Command::Move { unit_id: uid, to: *pos });
                }
            }
        }

        None
    }
}

/// No-op strategy for GOAP actions (we don't use the Strategy pattern for execution)
#[derive(Debug)]
struct NoOpStrategy;
impl telic::planning::action::Strategy for NoOpStrategy {
    fn is_complete(&self) -> bool { true }
}


impl HybridAgent {
    fn compute_command(&mut self, view: &SimpleWarsView) -> Command {
        self.actions_this_turn += 1;
        if self.actions_this_turn > 30 {
            self.actions_this_turn = 0;
            return Command::EndTurn;
        }

        // Layer 1: GOAP build decisions
        let hq_free = !view.our_units.iter().any(|u| u.pos == view.our_hq);
        if hq_free {
            let build = match &self.current_strategy {
                StrategicAction::BuildCapturers => {
                    if view.our_gold >= UnitType::Infantry.cost() {
                        Some(UnitType::Infantry)
                    } else { None }
                }
                StrategicAction::BuildArmy => {
                    if view.our_gold >= UnitType::Tank.cost() {
                        Some(UnitType::Tank)
                    } else if view.our_gold >= UnitType::Infantry.cost()
                        && view.our_units.iter().filter(|u| u.unit_type.can_capture()).count() < 3
                    {
                        Some(UnitType::Infantry)
                    } else { None }
                }
                _ => {
                    // Other strategies: build opportunistically
                    let infantry = view.our_units.iter().filter(|u| u.unit_type.can_capture()).count();
                    let total = view.our_units.len();
                    if total < 6 && infantry < 3 && view.our_gold >= UnitType::Infantry.cost() {
                        Some(UnitType::Infantry)
                    } else if total < 6 && view.our_gold >= UnitType::Tank.cost() {
                        Some(UnitType::Tank)
                    } else { None }
                }
            };

            if let Some(unit_type) = build {
                if view.our_gold >= unit_type.cost() {
                    return Command::Build { unit_type };
                }
            }
        }

        // Layer 2: Generate all tasks with GOAP-driven weight modifiers
        // (HTN enriches attack tasks near capture targets)
        let tasks = self.generate_all_tasks(view);

        // Layer 3: Utility assignment of units to tasks
        let assignments = self.assign_units(&tasks, view);

        for (uid, task) in &assignments {
            let unit = match view.our_units.iter().find(|u| u.id == *uid) {
                Some(u) => u,
                None => continue,
            };
            if unit.moved && unit.attacked { continue; }
            if let Some(cmd) = self.execute_unit(unit, task, view) {
                return cmd;
            }
        }

        self.actions_this_turn = 0;
        Command::EndTurn
    }
}

impl GameAgent<SimpleWarsView, Command> for HybridAgent {
    fn name(&self) -> &str { &self.name }

    fn reset(&mut self, player: PlayerIndex) {
        self.player = player;
        self.actions_this_turn = 0;
        self.explored.clear();
        self.map_rows = 0;
        self.map_cols = 0;
        self.last_known_enemies.clear();
        self.current_strategy = StrategicAction::BuildCapturers;
        self.strategy_turns = 0;
    }

    fn observe(&mut self, view: &SimpleWarsView) {
        if self.explored.is_empty() {
            self.map_rows = view.rows;
            self.map_cols = view.cols;
            self.explored = vec![vec![false; view.cols as usize]; view.rows as usize];
        }
        for r in 0..view.rows as usize {
            for c in 0..view.cols as usize {
                if view.visibility[r][c] { self.explored[r][c] = true; }
            }
        }
        for enemy in &view.visible_enemy_units {
            self.last_known_enemies.retain(|(p, _)| *p != enemy.pos);
            self.last_known_enemies.push((enemy.pos, view.turn));
        }
        self.last_known_enemies.retain(|(_, turn)| view.turn - turn < 10);

        // Re-evaluate strategy every observation (GOAP replanning)
        let new_strategy = self.evaluate_strategy(view);
        if new_strategy != self.current_strategy {
            self.current_strategy = new_strategy;
            self.strategy_turns = 0;
        } else {
            self.strategy_turns += 1;
        }
    }

    fn decide(
        &mut self,
        view: &SimpleWarsView,
        tree: &CommandTree<Command>,
    ) -> Option<Command> {
        crate::ai::tree_helpers::propose_and_validate(tree, || self.compute_command(view))
    }
}
